# Generated by Django 4.1.7 on 2023-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
